sudo: false

language: python

python:
 - "3.5"

addons:
  apt:
    packages:
    - parallel

install:
  - pip install http://ftp.openquake.org/python-new-wheels/Cython-0.23.4-cp35-cp35m-manylinux1_x86_64.whl
  - pip install http://ftp.openquake.org/python-new-wheels/numpy-1.11.1-cp35-cp35m-manylinux1_x86_64.whl
  - pip install http://ftp.openquake.org/python-new-wheels/scipy-0.17.1-cp35-cp35m-manylinux1_x86_64.whl
  - pip install http://ftp.openquake.org/python-new-wheels/Shapely-1.5.13-cp35-cp35m-manylinux1_x86_64.whl
  - pip install http://ftp.openquake.org/python-new-wheels/h5py-2.6.0-1-cp35-cp35m-manylinux1_x86_64.whl
  - python setup.py develop

script:
  - nosetests --with-doctest -v -a'!slow'
